name: Deployment
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - "config/**"
      - "test/**"
      - ".github/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ðŸ•Š Deploy
    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
      - name: ðŸ— Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6
          run_install: false

      - name: ðŸ— Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: â¬‡ Install
        run: pnpm install --frozen-lockfile

      - name: ðŸ“¦ Build
        run: pnpm run build

      - name: ðŸš€ Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            echo "kv_namespaces = [{binding=\"URLS\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
            echo "[site]" >> wrangler.toml
            echo "bucket = '../remix-app/public'" >> wrangler.toml
          secrets: |
            ACCESS_KEY
            DISSALLOWED_DOMAINS
            APP_URL
          workingDirectory: "packages/worker"
          command: publish
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          DISSALLOWED_DOMAINS: ${{ secrets.DISSALLOWED_DOMAINS }}
          APP_URL: ${{secrets.APP_URL }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
